.\"                                      Hey, EMACS: -*- nroff -*-
.TH crfsuite 1 "Mar  6, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
crfsuite \- CRFsuite command-line frontend
.SH SYNOPSIS
.B crfsuite
.RB [ -c | -u "] [" -t
.IR csv-word-list ]
.RB [ -p " [" -P
.IR source-dir "] [" -r "] [" -f "] [" -i "]]" 
.RB [ -R " [" -L 
.IR level "]]"
.RB [ -d
.IR device-id ]
.RB [ -s
.IR name:value ]
.RB [ -e
.IR system-encoding ]
.RB [ -w
.IR tag-encoding]
.RI [ mount-point ]
.br
.BR "crf " [ -h | -x | -v | -l ]

.SH DESCRIPTION
\fBcrfsuite\fP is a command line utility.

.br
.SH AUTHORS
\fBcrfsuite\fP was written by Naoaki Okazaki
<okazaki at chokkan dot org>.
